version: "3.7"

services:
  app:
    image: ghcr.io/t0bst4r/home-assistant-matter-hub:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${APP_DATA_DIR}:/data
    environment:
      HAMH_LOG_LEVEL: info
      HAMH_HTTP_PORT: 8482
